### ISSUE TITLE
Fix Permission denied: '/var/lib/ckan/storage/uploads/group'

### ISSUE THREAD

**Issue by brunopacheco1** [ckan/ckan-docker-base#41]
## What

I am building a custom docker image for CKAN in the following repo: https://github.com/GenomicDataInfrastructure/gdi-userportal-ckan-docker

But I got he logs below, when running that image in this docker compose definition: https://github.com/GenomicDataInfrastructure/gdi-userportal-ckan-deployment

```
gdi-userportal-ckan-deployment-ckan-1  | 2023-12-27 20:11:46,577 INFO  [ckan.config.middleware.flask_app]  200 /api/i18n/en render time 0.010 seconds
gdi-userportal-ckan-deployment-ckan-1  | 2023-12-27 20:12:11,074 ERROR [ckan.config.middleware.flask_app] [Errno 13] Permission denied: '/var/lib/ckan/storage/uploads/group'
gdi-userportal-ckan-deployment-ckan-1  | Traceback (most recent call last):
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
gdi-userportal-ckan-deployment-ckan-1  |     rv = self.dispatch_request()
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
gdi-userportal-ckan-deployment-ckan-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/site-packages/flask/views.py", line 84, in view
gdi-userportal-ckan-deployment-ckan-1  |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/site-packages/flask/views.py", line 158, in dispatch_request
gdi-userportal-ckan-deployment-ckan-1  |     return current_app.ensure_sync(meth)(*args, **kwargs)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/config/middleware/../../views/group.py", line 862, in post
gdi-userportal-ckan-deployment-ckan-1  |     group = _action(u'group_create')(context, data_dict)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 580, in wrapped
gdi-userportal-ckan-deployment-ckan-1  |     result = _action(context, data_dict, **kw)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/logic/action/create.py", line 946, in organization_create
gdi-userportal-ckan-deployment-ckan-1  |     return _group_or_org_create(context, data_dict, is_org=True)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/logic/action/create.py", line 739, in _group_or_org_create
gdi-userportal-ckan-deployment-ckan-1  |     upload = uploader.get_uploader('group')
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/lib/uploader.py", line 61, in get_uploader
gdi-userportal-ckan-deployment-ckan-1  |     upload = Upload(upload_to, old_filename)
gdi-userportal-ckan-deployment-ckan-1  |   File "/srv/app/src/ckan/ckan/lib/uploader.py", line 129, in __init__
gdi-userportal-ckan-deployment-ckan-1  |     os.makedirs(self.storage_path)
gdi-userportal-ckan-deployment-ckan-1  |   File "/usr/lib/python3.10/os.py", line 225, in makedirs
gdi-userportal-ckan-deployment-ckan-1  |     mkdir(name, mode)
gdi-userportal-ckan-deployment-ckan-1  | PermissionError: [Errno 13] Permission denied: '/var/lib/ckan/storage/uploads/group'
gdi-userportal-ckan-deployment-ckan-1  | 2023-12-27 20:12:11,111 INFO  [ckan.config.middleware.flask_app]  500 /organization/new render time 0.061 seconds
```
## Hotfix for debuging
If I access the container and create the folder manually, the problem is fixed.

If I add `RUN chmod u+rwx "/var/lib/ckan"` to the end of my custom dockerfile, the problem is fixed.

## Question

Does it make sense to replace line 93 and 94 from ckan-base [Dockerfile](
https://github.com/ckan/ckan-docker-base/blob/cbd8878de7a234d4187fd8669b40f4bce80f6692/ckan-2.10/base/Dockerfile#L93C1-L94C44) by the following command?
```
RUN mkdir -p ${CKAN_STORAGE_PATH} && \
    chown -R ckan:ckan ${CKAN_STORAGE_PATH} && \
    chmod u+rwx ${CKAN_STORAGE_PATH}
```

**Comment by kowh-ai** [comment]
I have just tested your "Steps to Reproduce" and I don't get the same behaviour. I don't get an error. 

What do you mean by a "custom image" I'm building and running the CKAN image from https://github.com/ckan/ckan-docker/tree/master/ckan which by default is using the  CKAN **base** image from https://github.com/ckan/ckan-docker-base/tree/main/ckan-2.10/base

**Comment by dev-rke** [comment]
I have this issue, too, when creating new organisations.
Currently i am using 
```Dockerfile
FROM ckan/ckan-base:2.10.4
```
in my Dockerfile to create a custom image, so it's the production image, not the DEV image.
System is Ubuntu 22.04, Docker 24.0.5.

Directory structure + permissions:
```
08a46e208f94:/var/lib/ckan# ls -lah
total 20K    
drwxr-xr-x    1 ckan     ckan        4.0K May 23 10:07 .
drwxr-xr-x    1 root     root        4.0K Mar 13 11:34 ..
drwxr-xr-x    3 root     root        4.0K May 23 10:07 storage
drwxr-xr-x    7 ckan     ckan        4.0K May 23 09:07 webassets
08a46e208f94:/var/lib/ckan# ls -lah storage
total 12K    
drwxr-xr-x    3 root     root        4.0K May 23 10:07 .
drwxr-xr-x    1 ckan     ckan        4.0K May 23 10:07 ..
drwxr-xr-x    3 root     root        4.0K May 23 10:07 uploads
08a46e208f94:/var/lib/ckan# ls -lah storage/uploads
total 12K    
drwxr-xr-x    3 root     root        4.0K May 23 10:07 .
drwxr-xr-x    3 root     root        4.0K May 23 10:07 ..
drwxr-xr-x    2 root     root        4.0K May 23 10:07 user
```

As you can see, the directory structure has been created by root user, instead of the ckan user.

The proposed approach, to change permissions via `chmod u+rwx /var/lib/ckan` did not solve the issue on my side - at least this needs to be recursive, but won't work, when the storage folder will be created later.
The main issue seems to be, that CKAN creates the `storage` folder as root user, instead applying the ckan user of the uswgi service.
I assume, the reason could be, that the CLI CKAN command is always executed as root user, instead of running it as regular user and creates the folder with root permissions.

Is there any downside to introduce after Line https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.10/base/Dockerfile#L95 
a command like 
```Dockerfile
USER ckan
```
to ensure any further filesystem changes will be in context of the ckan user?
Also from a security perspective this approach might be better, as it reduces possible attack vectors against the container.
To install further applications via pip, a developer can always switch to root mode manually.

What do you think?
